# General Configurations
add_newline = false
palette = "onedark"

# Format Configurations
format = """
[](black_light)\
[ ](fg:white bg:black_light)\
[](fg:black_light bg:black_dark)\
$directory\
[](fg:black_dark bg:black)\
$git_branch\
$git_status\
[](black)\
$fill\
$python\
$line_break\
$character\
"""

# Colour Configurations
[palettes.onedark]
black_light = "#3a3f4b"
black_dark = "#31363f"
black = "#282c34"
grey = "#5c6370"
white = "#abb2bf"
red = "#e06c75"
blue = "#61afef"
cyan = "#56b6c2"
green = "#98c379"
purple = "#c678dd"
orange = "#d19a66"
yellow = "#e5c07b"

# Layout Configurations
[character]
success_symbol = "[](bold green)"
error_symbol = "[](bold red)"
disabled = false

[fill]
symbol = "-"
style = "white"
disabled = false

# Directory Configurations
[directory]
style = "fg:white bg:black_dark"
format = "[  $path ]($style)"
truncation_symbol = "…/"
truncate_to_repo = true
disabled = false

[directory.substitutions]
"~/Documents/Codebase" = "…/Codebase"

# Git Configurations
[git_branch]
style = "fg:white bg:black"
format = '[ $symbol $branch]($style)'
symbol = ""
truncation_symbol = "…"
disabled = false

[git_status]
style = "fg:white bg:black"
format = '[ ($all_status$ahead_behind )]($style)'
deleted = "x"
disabled = false

# Language Configurations
[python]
symbol = "󰌠"
style = "fg:white bg:black_dark"
format = '[](black_dark)[ $symbol( $virtualenv) ]($style)[](black_dark)'
disabled = false
